Change the SaveData class to MinecraftCreeper to make it clearer for
League-central/java-modules pull request #211
Opened 2020-10-14 19:04 UTC by DaveDLeague

students who think SaveData is a java class that is required for
serialization.

2020-11-19 18:06 UTC, dencee requested changes

2020-11-19 18:06 UTC, dencee commented on Level5-Module1/src/_05_Serialization/Serialization.java
>  		// Construct a SaveData object and save it to a file
In comment, change to 'MinecraftCreeper object'

2020-11-19 18:06 UTC, dencee commented on Level5-Module1/src/_05_Serialization/Serialization.java
>  		// Load the SaveData object from the file
In comment, change to 'MinecraftCreeper object'

2020-12-03 18:40 UTC, DaveDLeague commented on Level5-Module1/src/_05_Serialization/Serialization.java
>  		// Load the SaveData object from the file
Fixed

2020-12-03 18:40 UTC, merged