Added recipe about pseudo random number generation
League-central/java-modules pull request #213
Opened 2020-10-20 19:15 UTC by DaveDLeague

2020-11-19 17:55 UTC, dencee requested changes

2020-11-19 17:55 UTC, dencee commented on Level5-Module4/src/_03_Printing_Binary/BinaryPrinter.java
> +		// We first want to print the bit in the one's place
Can this be changed to say something like, "We first want to print the leftmost bit and the following bits to the right."?

2020-11-19 18:46 UTC, dencee requested changes

2020-11-19 18:46 UTC, dencee commented on Level5-Module4/src/_05_Pseudo_RNG/PseudoRNG.java
> +	long xorShift(long seed){
For this example, I believe the RNG seed should be a member variable that the xorShift method continually processes the seed member variable to produce a random num. So the code would be:
private long seed; // member variable
public PseudoRNG( long seed ){ this.seed = seed; }
public long xorShift() { // code }

2020-11-19 18:46 UTC, dencee commented on Level5-Module4/src/_05_Pseudo_RNG/PseudoRNG.java
> +		//     use System.currentTimeMillis as the seed to get
Can step 11 mention to create a PseudoRNG object with a specific seed, print xorShift() 3 times and note the random numbers, then do the same thing with a different seed and notice the 3 numbers are different? Then rerun the tests a second time and notice that 3 random numbers are the same because the seed generates the same sequence of random numbers?

2021-01-05 23:04 UTC, DaveDLeague commented on Level5-Module4/src/_03_Printing_Binary/BinaryPrinter.java
> +		// We first want to print the bit in the one's place
changes applied

2021-01-05 23:04 UTC, DaveDLeague commented on Level5-Module4/src/_05_Pseudo_RNG/PseudoRNG.java
> +		//     use System.currentTimeMillis as the seed to get
changes applied

2021-01-05 23:04 UTC, DaveDLeague commented on Level5-Module4/src/_05_Pseudo_RNG/PseudoRNG.java
> +	long xorShift(long seed){
changes applied

2021-01-05 23:07 UTC, keithagroves approved these changes

2021-01-05 23:08 UTC, merged