L1M4-Jeopardy-Update
League-central/java-modules pull request #248
Opened 2021-03-09 23:30 UTC by ColbySchexnayder

Added a few minor tweaks that I missed when updating the sound.

The file will be correctly opened in the same thread now and can be stopped from playing to keep with the instructions.

2021-03-11 19:02 UTC, dencee requested changes
Can this code either:
1) mention using the clip variable to stop the music in the instructions
OR
2) change the clip variable name to more easily indicate it controls the theme music, e.g. themeMusicClip, jeopardyThemeClip.

2021-04-05 21:17 UTC, ColbySchexnayder commented
I changed the name of the variable like you suggested but for this recipe I imagined that they would call the stopJeopardyTheme() method to match how they call the playJeopardyTheme()

2021-04-08 22:57 UTC, dencee approved these changes

2021-04-08 22:57 UTC, dencee commented
Adding a stop method also works!

2021-04-08 22:58 UTC, merged