L3: Additional 2D array practice
League-central/java-modules pull request #250
Opened 2021-03-23 20:23 UTC by dencee

2021-04-13 23:01 UTC, ColbySchexnayder requested changes

2021-04-13 23:01 UTC, ColbySchexnayder commented on Level3-Module0/src/_03_Intro_to_2D_Arrays/_02_2DArrayPractice.java
> +     * second column (column 1)
The instruction asks for the sum of the second column but the test checks for the sum of the first

2021-04-13 23:57 UTC, dencee commented on Level3-Module0/src/_03_Intro_to_2D_Arrays/_02_2DArrayPractice.java
> +     * second column (column 1)
Fixed!

2021-04-14 17:01 UTC, ColbySchexnayder approved these changes

2021-04-14 17:01 UTC, merged