L1 m0 repackaging with starter code for processing apps
League-central/java-modules pull request #251
Opened 2021-04-03 01:11 UTC by jaLeague

Please synch these changes with the parallel changes to the curriculum pages reflecting the same.

2021-04-06 20:41 UTC, ColbySchexnayder requested changes
It looks good but it looks like the answers were left in DuelingButtons.java and a small typo in the package name. The package is duelling but the recipe is dueling

2021-04-09 22:19 UTC, dencee requested changes
Fortune folder is misspelled
Level1-Module0/src/_03_gui_from_scratch/_1_forunte_cookie/recipe.html

2021-04-09 22:20 UTC, dencee commented
What are your plans with the simple collision demo?

2021-04-10 00:02 UTC, jaLeague commented on Level1-Module0/src/_02_gui_with_help/_5_duelling_buttons/DuelingButtons.java
> +frame.add(panel);
Removed solution

2021-04-10 00:03 UTC, jaLeague commented on Level1-Module0/src/_02_gui_with_help/_3_drum_kit/DrumKit.java
> +		if (canPlaySounds) {
File should now be consistent

2021-04-10 00:03 UTC, jaLeague commented
> It looks good but it looks like the answers were left in DuelingButtons.java and a small typo in the package name. The package is duelling but the recipe is dueling

Classes now consistent with package

2021-04-10 00:04 UTC, jaLeague commented
I believe this is now ready for merging.

2021-04-10 00:06 UTC, merged