L0M1 - Robot in Space - Sound Update
League-central/java-modules pull request #253
Opened 2021-04-05 22:37 UTC by ColbySchexnayder

Removing the deprecated JApplet used for sound and replacing it with AudioSystem

2021-04-08 23:27 UTC, dencee requested changes
This file also has a mix of tabs and spaces.

2021-04-08 23:27 UTC, dencee commented on Level0-Module1/src/_04_int/_2_robot_in_space/RobotInSpace.java
should be: KeyboardAdapter
with a lower case 'b'

2021-04-08 23:27 UTC, dencee commented on Level0-Module1/src/_04_int/_2_robot_in_space/RobotInSpace.java
> +		checkIfR2D2Found();
Surround with try catch because checkIfR2D2Found() throws Exception

2021-04-08 23:27 UTC, dencee commented on Level0-Module1/src/_04_int/_2_robot_in_space/RobotInSpace.java
> +
Why are these variables volatile?

2021-04-13 23:43 UTC, dencee requested changes

2021-04-13 23:43 UTC, dencee commented on Level0-Module1/src/_04_int/_2_robot_in_space/RobotInSpace.java
> +	 * 1. IMPORTANT: For this recipe, use rob.microMove(distance) to move your Robot
Since the microMove() method throws InterruptedException, can to the moveRobot() method add a throws InterruptedException and try-catch the run() method instead so the students don't have to put in the try-catch blocks when they write their code?

private void moveRobot(int keyPressed) throws InterruptedException {

2021-04-14 17:17 UTC, ColbySchexnayder commented on Level0-Module1/src/_04_int/_2_robot_in_space/RobotInSpace.java
> +	 * 1. IMPORTANT: For this recipe, use rob.microMove(distance) to move your Robot
microMove() isn't actually needed anymore. move() works fine and doesn't throw an exception. I just changed the instruction.

2021-04-14 21:23 UTC, dencee approved these changes

2021-04-14 21:23 UTC, merged