L0 m5/method writing
League-central/java-modules pull request #273
Opened 2021-10-22 18:30 UTC by tylercwiltz

I added two recipes to help with writing methods with parameters and return types. 
1) IntroToMethods shows students the different options for methods with and without parameters and different return types. The students can look at the code and run it to see the outputs.
2) Calculator has the students make add, subtract, multiply, and divide methods and then call those methods.

Let me know any suggestions or any other new recipe ideas for writing methods.

2021-11-29 21:49 UTC, dencee requested changes

2021-11-29 21:49 UTC, dencee commented on Level0-Module5/src/_03_method_writing/_1_intro_to_methods/IntroToMethods.java
> +
Reformat file to use either all spaces or all tabs (see line 9)

2021-11-29 21:49 UTC, dencee commented on Level0-Module5/src/_03_method_writing/_1_intro_to_methods/IntroToMethods.java
> +	 * 		* ALways inside the ()
uppercase L in always

2021-11-29 21:49 UTC, dencee commented on Level0-Module5/src/_03_method_writing/_1_intro_to_methods/IntroToMethods.java
> +	 */
Is there a way we can close the loop on the "figure out" direction? I'm envisioning students running the file and just moving on.

2021-11-29 21:49 UTC, dencee commented on Level0-Module5/src/_03_method_writing/_1_intro_to_methods/IntroToMethods.java
> +	 * 		* Always directly to the left of the method name
Can you add an explanation for a void return because void isn't a type in Java.

2021-11-29 21:49 UTC, dencee commented on Level0-Module5/src/_03_method_writing/_4_calculator/Calculator.java
> +
Reformat file to use either all spaces or all tabs (see lines 22, 23)

2021-11-29 21:49 UTC, dencee commented on Level0-Module5/src/_03_method_writing/_1_intro_to_methods/IntroToMethods.java
> +	 * LOOK AT THE CODE BELOW AND FIGURE OUT THE 3 PARTS TO EACH METHOD
Inevitably the students will ask what the "public static" part of the example methods do. I think a bullet point along the lines of "public is optional and use static if calling the method from main" would be good.

2021-11-30 00:55 UTC, tylercwiltz commented on Level0-Module5/src/_03_method_writing/_4_calculator/Calculator.java
> +		// 4) Call the result() method and put the answer in a pop-up
I know it's less practical, but my intention was this would help student's understand return types as well. So do you still think I should change it?

2021-11-30 01:39 UTC, dencee commented on Level0-Module5/src/_03_method_writing/_4_calculator/Calculator.java
> +		// 4) Call the result() method and put the answer in a pop-up
Nah, it's just a minor thing.

2021-11-30 18:55 UTC, dencee approved these changes

2021-11-30 19:17 UTC, merged