Split up sleepy head into four separate recipes
League-central/java-modules pull request #276
Opened 2021-10-31 23:20 UTC by codybsauer

New recipes match the old assignments in spirit, but get into more
details about how booleans can be used and provide a gradual progression
of topics.

-Sleepy head uses a boolean in an if-else statement
-Star student uses a boolean in a method and introduces the not operator
-Game over uses a boolean in a while loop
-Red Square uses multiple booleans with and/or operators

2021-11-02 21:37 UTC, ColbySchexnayder requested changes
I like this a lot better than what we had. The package names jump from 4 to 6 at googly eyes though

2021-11-03 00:05 UTC, tylercwiltz reviewed
Just a few suggestions and a few typos I noticed. Overall, I think this is a more practical use of booleans than what we had and splitting it up will hopefully be less confusing/more enjoyable for the students.

2021-11-03 00:05 UTC, tylercwiltz commented on Level0-Module4/src/_02_boolean/_4_red_square/RedSquare.java
> +		// 9. Keep rerunning the program and change the isRed and isSquare
typo change "step 5" to "step 6"

2021-11-03 00:05 UTC, tylercwiltz commented on Level0-Module4/src/_02_boolean/_4_red_square/RedSquare.java
> +		// 7. Write an if statement using the static booleans at the top of
Maybe mention something about how those booleans are set in the draw methods below? Just so it's clear to the students that calling that method could change the value of the boolean from what it is initialized to at the top of the code.

2021-11-08 18:11 UTC, codybsauer commented on Level0-Module4/src/_02_boolean/_4_red_square/RedSquare.java
> +		// 4. Write an else if statement that calls drawRedTriangle() is isRed
fix'd

2021-11-08 18:12 UTC, codybsauer commented on Level0-Module4/src/_02_boolean/_4_red_square/RedSquare.java
> +		// 6. Keep rerunning your program, initializing isRed and IsSquare to
fixed

2021-11-08 18:13 UTC, codybsauer commented on Level0-Module4/src/_02_boolean/_4_red_square/RedSquare.java
> +		// 9. Keep rerunning the program and change the isRed and isSquare
fixed

2021-11-08 18:51 UTC, codybsauer commented on Level0-Module4/src/_02_boolean/_4_red_square/RedSquare.java
> +		// 7. Write an if statement using the static booleans at the top of
Added:
		//    Notice these static booleans start off false, but update to true 
		//    whenever you call their matching method.

2021-11-08 19:50 UTC, tylercwiltz approved these changes

2021-11-11 00:23 UTC, jaLeague commented
I like the changes. 
Minor comment. RedSquare #1 says "notice drawRedSquare is not called". The student does not know if it is not called or the program just isn't working. It would be nice to have an else that confirmed program ran but did not draw anything. The else statement could stay around even after the else if's are added later. Always good to encourage an else statement any way :)

2021-12-10 17:43 UTC, keithagroves approved these changes

2021-12-16 18:42 UTC, merged