Level 1 Return Type Recipes
League-central/java-modules pull request #290
Opened 2021-12-21 21:57 UTC by tylercwiltz

3 recipes on return types.  Solutions are in a branch called L1M1-ReturnTypeRecipesSolutions.

2021-12-22 00:11 UTC, dencee requested changes
Rest looks good!

2021-12-22 00:11 UTC, dencee commented on Level1-Module0/src/_02_return_types/_3_too_many_shapes/TooManyShapes.java
> +		int angle = 180-(((numSides-2)*180)/numSides);
Still works, but how did you get this equation? If you simplify it, it's just angle = 360 / numSides
angle = 180 - (180*n - 360) / n
angle = 180 - 180*n/n + 360/n
angle = 180 - 180 + 360/n
angle = 360/n

2021-12-22 00:11 UTC, dencee commented on Level1-Module0/src/_02_return_types/_3_too_many_shapes/TooManyShapes.java
> +	    		rob.move(dist);
mixed spaces and tabs here

2021-12-22 16:35 UTC, tylercwiltz commented on Level1-Module0/src/_02_return_types/_3_too_many_shapes/TooManyShapes.java
> +		int angle = 180-(((numSides-2)*180)/numSides);
Nice catch.  Idk why I had it the other way.  This was an older recipe I wrote that I modified, but I can't remember if there was a reason I did it that way.

2021-12-22 16:38 UTC, tylercwiltz commented on Level1-Module0/src/_02_return_types/_3_too_many_shapes/TooManyShapes.java
> +	    		rob.move(dist);
I checked them and they all seem to be tabs.  I tabbed them again just to be sure, but it looks all good on my end. So let me know if it's still wonky.

2021-12-29 19:44 UTC, dencee approved these changes

2021-12-29 19:44 UTC, merged