L1M0 - Asteroids Game to Teach Constructors
League-central/java-modules pull request #292
Opened 2022-01-03 21:21 UTC by ColbySchexnayder

Added the Asteroids game to the end of the methods package in Level 1 Module 0

2022-01-14 18:22 UTC, dencee requested changes
*This project should be moved out of the methods package to somewhere after L1M1 where constructors are introduced.
*The curriculum website needs to be updated to where ever this project ends up.

2022-01-14 18:22 UTC, dencee commented on Level1-Module0/src/_01_methods/_5_ConstructorsAsteroids/Asteroid.java
> +			x = AsteroidsGame.WIDTH;
This file contains a mix of spaces and tabs

2022-01-14 18:22 UTC, dencee commented on Level1-Module0/src/_01_methods/_5_ConstructorsAsteroids/AsteroidsGame.java
> +	 * However if you tried running this you'll notice that we get a NullPointerException
Instead of throwing a null ptr exception can you have the code fail gracefully somehow? Possibly a message saying the rocket constructor needs to be created? Keith told me it's a "rule" that all the curriculum code is supposed to be in a state where it can run without errors.

2022-01-19 00:04 UTC, ColbySchexnayder commented
The recipe was moved to the early in the constructors section of module 1 since it's supposed to be a basic introduction.
The website has a pull request to reflect this.
The formatting for Asteroids.java has been fixed.
Instead of throwing a null pointer exception, the program will popup a message telling the user to make a constructor then exit.

2022-01-20 04:45 UTC, dencee approved these changes

2022-01-20 21:29 UTC, merged