All sounds & speak replaced by Sound class from game_tools
League-central/java-modules pull request #305
Opened 2022-02-23 23:46 UTC by dencee

2022-02-26 21:17 UTC, ColbySchexnayder requested changes

2022-02-26 21:17 UTC, ColbySchexnayder commented on Level1-Module0/src/_03_gui_with_help/_3_drum_kit/DrumKit.java
> +		// You can use the drum sound provided ("drum.wav") or
This worked with cymbal.wav but I got this error trying to use drum.wav: ERROR: line with format PCM_SIGNED 44100.0 Hz, 24 bit, stereo, 6 bytes/frame, little-endian not supported. for src/_03_gui_with_help/_3_drum_kit/drum.wav

2022-02-26 21:17 UTC, ColbySchexnayder commented on Level1-Module4/src/_05_fortune_teller/FortuneTeller.java
> +        Sound sound = new Sound(fileName);
This should use the package name, right now it can't find the file

2022-03-02 06:28 UTC, dencee commented on Level1-Module4/src/_05_fortune_teller/FortuneTeller.java
> +        Sound sound = new Sound(fileName);
When using the instructions above it seems to play the sound ok.
            // 8. Find a spooky sound and put it in your _05_fortune_teller package (freesound.org)
            //    play("_05_fortune_teller/creepy-noise.wav");

2022-03-02 20:11 UTC, ColbySchexnayder approved these changes

2022-03-02 20:11 UTC, merged